---
language: python

python:
  - "2.7"
  - "3.6"

services:
  - docker

install:
  - pip install molecule docker

before_script:
  - molecule --version
  - ansible --version

env:
  - SCENARIO=default
  - SCENARIO=centos

script:
  - "molecule test -s $SCENARIO"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
