---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu1404
    image: ubuntu:14.04
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubuntu1804
    image: ubuntu:18.04
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["503"]
verifier:
  name: testinfra
  lint:
    name: flake8
