---
- name: Converge
  hosts: all
  roles:
    - role: ansible-postgresql
      vars:
        postgresql_users:
          - name: 'pgpool'
            password: 'pgpool'
            role_attr_flags: 'REPLICATION,LOGIN,NOCREATEROLE,NOCREATEDB'
            state: 'present'
